apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend-deployment
    namespace: exsys-staging
spec:
    replicas: 1
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 0
            maxSurge: 1
    selector:
        matchLabels:
            app: backend-deployment
    template:
        metadata:
            labels:
                app: backend-deployment
        spec:
            automountServiceAccountToken: false
            containers:
                - name: backend-deployment
                  resources:
                      limits:
                          cpu: "400m"
                          memory: "300M"
                      requests:
                          cpu: "250m"
                          memory: "200M"
                  image: "rhaversen/exsys-backend:387d031792a44e760fe68837a0f3a0e0b2b33969"
                  imagePullPolicy: Always
                  livenessProbe:
                      httpGet:
                          path: service/livez
                          port: 5000
                      periodSeconds: 10
                      initialDelaySeconds: 15
                      failureThreshold: 5
                  readinessProbe:
                      httpGet:
                          path: service/readyz
                          port: 5000
                      periodSeconds: 10
                      initialDelaySeconds: 15
                      failureThreshold: 5
                  ports:
                      - containerPort: 5000
                  envFrom:
                      - secretRef:
                            name: backend-secrets
